### ISSUE TITLE
handle 404

### ISSUE THREAD

**Issue by mitchellirvin** [noelleirvin/blog#3]
the DNS routing will route requests `thisgoodendeavor.com/*` to `thisgoodendeavor.com`, where react-router will then take over and load the correct page (so the page request is handled client-side, not server-side).

if you enter `thisgoodendeavor.com/foo`, you'll just end up with a page with no post loaded. We should implement a catch-all route for the case where the URL doesn't match an existing post

**Comment by noelleirvin** [comment]
fixed in PR 17
