### ISSUE TITLE
Add loading bar/spinner to homepage

### ISSUE THREAD

**Issue by mitchellirvin** [noelleirvin/blog#6]
Now that there are more than a few posts, it takes a non trivial amount of time for them to load on the home page. We might want to look into how to parallelize/optimize this, but in general it's probably a good idea to have a spinner while it loads.

![homepage_loading](https://user-images.githubusercontent.com/16233245/83331852-597dc500-a266-11ea-8962-d2cd30e62b3c.gif)

An aside, we're async/awaiting the calls to load the posts. That's probably where the lag is coming from

**Comment by noelleirvin** [comment]
Did you have a loader in mind?

**Comment by mitchellirvin** [comment]
Defer to my lovely designer!
